### ISSUE TITLE
Week of 11.16.15

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#316]
Question Of The Week:

_How might we better service our community?_

Tasks:

- [ ] Positive 10% Slack growth(@hellyeah)
- [ ] Upload last week's metrics to spreadsheet(@hellyeah)
- [ ] Create metrics repo(@hellyeah)
- [ ] Discuss with club leaders what curriculum they will run in their meeting and create any materials that are needed (@jonleung, #313)
- [ ] Plan (or cancel) 6 pairing calls(@hellyeah)
- [x] Plan (or cancel) weekly calls(@jonleung, #304)
- [x] Chatting with club leaders who haven't filled in data in the spreadsheet(@MaxWofford, #262)
- [ ] Collect curriculum and attendance data from meetings this week(@MaxWofford, #315)
- [x] Deprecate case studies(@zachlatta, hackedu#499)
- [ ] Publicly rename to Hack Club(@zachlatta, #310)
  - [x] Finalized version of Hack Strikes Back logo(@MaxWofford, #307)
- [x] Organize meeting about club leader communication (inactivity on Slack)(@MaxWofford, #314)
- [ ] Respond to all applicants(@zachlatta, #311)
- [ ] Document application review process(@zachlatta, #312)

**Comment by zachlatta** [comment]
Closing due to the week being over!

**Comment by zachlatta** [comment]
This week's issue is in #351.
