### ISSUE TITLE
Remove as many issues as possible from the ideas column

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#329]
- [x] Jonathan remove as many issues as possible from the ideas column #326
- [x] Max remove as many issues as possible from the ideas column #327
- [x] Zach remove as many issues as possible from the ideas column #328

**Comment by MaxWofford** [comment]
@jonleung Any updates on this?

**Comment by jonleung** [comment]
@MaxWofford done!
