### ISSUE TITLE
Week of 11.30.15

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#351]
- [ ] Onboard Selynna and Sam (hackclub/meta#317, @jonleung)
- [ ] Collect curriculum and attendance from last week and this week
  (hackclub/meta#350, @MaxWofford)
- [ ] Create another workshop (TODO, @jonleung)
- [ ] Make workshops README student facing (shorten it) (TODO, @jonleung)
  - [ ] Organize workshops into playlists (TODO, @jonleung)
- [x] Create GitHub shortlinks (hackclub/hackclub#343, @zachlatta)
  - [x] workshops.hackclub.io -> workshops/README.md
  - [x] gh.hackclub.io -> README.md
- [x] Add workshop feedback tables (hackclub/hackclub#520, @zachlatta)
  - [x] Markdown table of links between 1 and 10 and the question "How likely would
    you recommend this workshop to a friend?"
- [ ] Hack Club logo (hackclub/meta#338, @MaxWofford)
- [ ] hackclub.com/hackclub.org/hack.club (hackclub/meta#347, @zachlatta)
- [x] Organize another hack night (hackclub/meta#339, @MaxWofford)
- [ ] Make assets for the iOS track (hackclub/meta#340, @MaxWofford)
- [ ] Fix JSBin build system (hackclub/hackclub#521, @zachlatta)
- [ ] Rewrite CONTRIBUTING.md (hackclub/hackclub#512, @zachlatta)
- [ ] Respond to all applicants (hackclub/meta#311, @zachlatta)
- [x] Deploy `slack-stats-collector` (hackclub/meta#348, @zachlatta)
- [ ] Fix Hubot's contribution count (hackclub/meta#341, @MaxWofford)
- [x] Rename Hubot to Prophet Orpheus (hackclub/meta#342, @MaxWofford)
- [ ] Finish 6 month plan (hackclub/meta#349, @zachlatta)

Booyah. Let's do this.

@jonleung can you create issues for all of the TODOs and PM me links to them on Slack?

**Comment by MaxWofford** [comment]
UPDATE: I'm not planning on finishing Hubot's contribution count this week.

**Comment by zachlatta** [comment]
Closing this issue. Next week's is in #363.
