### ISSUE TITLE
Week of 12.07.15

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#363]
### Curriculum

- [x] Fix JSBin build system (hackclub/hackclub#521, @zachlatta)
- [ ] Copy Project Cipher's workshops to `hackclub/hackclub` (hackclub/meta#356,
  @jonleung)

### Meta

- [ ] Collect curriculum and attendance from last week and this week
  (hackclub/meta#350, @MaxWofford)
  - Clubs that were collected from last week:
    - [x] Armijo High School
    - [x] Glenaeon Rudolf Steiner School
    - [x] USC Hybrid School
    - [x] Project Cipher
    - [x] Ravenwood High School
    - [x] San Leandro High School
    - [x] South Brunswick High School
    - [ ] Elizabeth High School
    - [ ] San Mateo High School
    - [ ] Cherry Hill High School East
    - [ ] Lowell High School
  - Clubs to collect from this week:
    - [ ] Armijo High School
    - [ ] Glenaeon Rudolf Steiner School
    - [ ] USC Hybrid School
    - [ ] Project Cipher
    - [ ] Ravenwood High School
    - [x] San Leandro High School
    - [ ] South Brunswick High School
    - [ ] Elizabeth High School
    - [ ] San Mateo High School
    - [ ] Cherry Hill High School East
    - [ ] Lowell High School
- [x] De-onboard Dave (@zachlatta)
- [ ] Finish 6 month plan (hackclub/meta#349, @zachlatta)
- [ ] Fix Hubot's contribution count (hackclub/meta#341, @zachlatta)
- [ ] hackclub.com/hackclub.org/hack.club (hackclub/meta#347, @zachlatta)
- [x] Hack Club logo (hackclub/meta#338, @MaxWofford)
- [ ] Make assets for the iOS track (hackclub/meta#340, @MaxWofford)
- [x] Onboard Selynna and Sam (hackclub/meta#317, @jonleung)
- [ ] Respond to all applicants (hackclub/meta#311, @zachlatta)
- [ ] Rewrite CONTRIBUTING.md (hackclub/hackclub#512, ~~@zachlatta~~@paked)

/cc @hackclub/staff

**Comment by MaxWofford** [comment]
@zachlatta The iOS assets won't be finished this week because I'll be doing extra assets.

**Comment by zachlatta** [comment]
Alright, we've moved on to this week's issue #421
