### ISSUE TITLE
Implement HTML/CSS/JS styleguides

### ISSUE THREAD

**Issue by paked** [hackclub/meta#395]
Being tracked in:

- [ ] JavaScript #392, No PR
- [ ] HTML #393, No PR
- [x] CSS #394, #399  
- [x] English No issue, #398

**Comment by MaxWofford** [comment]
@paked I was looking at https://github.com/airbnb/javascript and noticed how clean their markdown files were. thoughts on doing this for markdown also?

**Comment by paked** [comment]
@MaxWofford we already have a markdown styleguide. Although, perhaps it would make sense to revisit it.

I'd just be wary that we would have to update every single markdown files once we make these changes.

**Comment by paked** [comment]
edit: Added English stylguide

**Comment by paked** [comment]
Update: English styleguide merged with #398

**Comment by zachlatta** [comment]
Thoughts on closing this? Since we're currently focused on implementing our new curriculum plan in hackclub/hackclub#778, this isn't a priority.

**Comment by zachlatta** [comment]
Going to go ahead and close this due to lack of response. If anyone wants to re-open this for discussion, go for it.
