### ISSUE TITLE
Week of 12.14.15

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#421]
- [ ] Rewrite CONTRIBUTING.md (hackclub/hackclub#512, @paked)
- [ ] Create how to submit a workshop (hackclub/hackclub#528, @jonleung)
- [ ] Facilitate the Learn To Code Series (hackclub/meta#400, @jonleung)
- [ ] Make assets for the iOS track (hackclub/meta#340, @MaxWofford)
- [ ] Create how to create a pull request workshop (hackclub/hackclub#568,
  @MaxWofford)
- [ ] Respond to all applicants (hackclub/meta#311, @zachlatta)
- [x] Update GOALS.md to reflect 6 month plan (hackclub/meta#349, @zachlatta)
- [x] Get hackclub.com (hackclub/meta#347, @zachlatta)
- [x] Setup The Hack Series (hackclub/meta#411, @zachlatta)

/cc @hackclub/staff

**Comment by zachlatta** [comment]
Going to go ahead and close this because the week's over. I'll link the next weekly issue here when we make it.

**Comment by zachlatta** [comment]
New weekly issue is in #450 :-).
