### ISSUE TITLE
Week of 01.04.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#450]
Primary goal: start 50 new clubs by the end of February.

-------------------------------------------------------------------------------

- [x] Create curriculum arc (@zachlatta, hackclub/hackclub#639)
- [x] Create general plan for first two meetings (@zachlatta, hackclub/hackclub#635)
- [x] Write document on the tools used in the clubs (@zachlatta, hackclub/hackclub#639)
- [ ] Incorporate tools we're using into the beginning workshops (@jonleung)
- [x] Add call checklist to onboarding checklist for new club leaders (@zachlatta)
- [x] Write and post semester 2 update for our clubs (@jonleung)
- [ ] Holiday update (~~@jonleung~~ @zachlatta, hackclub/meta#368)

@zachlatta is taking point on the planning of the curriculum this semester.
@jonleung will be building the actual content used in the meetings (like
workshops). We'll add tasks for to the list for @jonleung's work.

@zachlatta will also be passing off auxiliary work to @jonleung this week.

**Comment by jonleung** [comment]
@zachlatta, do we want to add these tasks from the code of conduct meeting we just had to this meta issue? I've pasted the tasks below:

- Add the following to events protocol (@jonleung)
  - An announcement about the code of conduct
  - An announcement of who the designated person is to talk to if you feel
    uncomfortable / if you think the code of conduct has been violated
- In `CONDUCT.md`, add that all official events run by Hack Club follow the code
  of conduct (@paked)
- Add code of conduct to the introduction presentation in the club guide
  (@jonleung)
- Add that the code of conduct should be covered in the onboarding document for
  club leader (@jonleung)
- Send announcement about the code of conduct in Slack (@zachlatta)
- Add code of conduct to the onboarding Slack document (@paked)

**Comment by jonleung** [comment]
@zachlatta, do we want to add the tasks that we came up with from the code of conduct meeting yesterday to this meta issue? If we choose not to add them, then I think it might be worthwhile for everyone to create issues for the below tasks on the board themselves, otherwise the tasks will not be reflected anywhere on the board.

Here are the tasks we came up with [that are in the meeting notes](https://github.com/hackclub/meta/issues/454):

- Add the following to events protocol (@jonleung)
  - An announcement about the code of conduct
  - An announcement of who the designated person is to talk to if you feel
    uncomfortable / if you think the code of conduct has been violated
- In `CONDUCT.md`, add that all official events run by Hack Club follow the code
  of conduct (@paked)
- Add code of conduct to the introduction presentation in the club guide
  (@jonleung)
- Add that the code of conduct should be covered in the onboarding document for
  club leader (@jonleung)
- Send announcement about the code of conduct in Slack (@zachlatta)
- Add code of conduct to the onboarding Slack document (@paked)

**Comment by jonleung** [comment]
Edit: I deleted one of my own extra comments above.

**Comment by zachlatta** [comment]
Yeah, can you create issues for the tasks in the meeting notes? Let's not
put them in the weekly issue and let them flow through the board like
regular issues.

On Thu, Jan 7, 2016 at 1:35 PM, Jonathan Leung <notifications@github.com>
wrote:

> Edit: I deleted one of my own extra comments above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/450#issuecomment-169812188>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Replaced by new weekly issue in #466.
