### ISSUE TITLE
Week of 01.11.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#466]
## Goals

- [ ] Workshops modified to use standardized tools in
  `hackclub/workshops/ARC.md`
- [x] Fully flesh out first two meetings in `hackclub/clubs/README.md`
- [x] 20 more people in applicant queue

-------------------------------------------------------------------------------

### Clubs

- [x] Write a section for each item in the schedule for the first and second
  meetings (in `hackclub/clubs/README.md`) (@zachlatta, hackclub/hackclub#647)
- [x] Get 20 more people in the applicant queue (@zachlatta, hackclub/meta#463)

### Workshops

- [ ] Modify Portfolio workshop to use standardized tools in
  `hackclub/workshops/ARC.md` (@jonleung, hackclub/hackclub#648)
- [ ] Modify Twilio workshop to use standardized tools in
  `hackclub/workshops/ARC.md` (@jonleung, hackclub/hackclub#649)
- [ ] Holiday update (@zachlatta, hackclub/meta#368)

### Meta

- [x] Send out semester 2 update to clubs (@zachlatta, hackclub/meta#464)

**Comment by zachlatta** [comment]
Closing because the week is over. New weekly issue is #481.
