### ISSUE TITLE
Week of 01.18.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#481]
**Big goals:**

- [x] Workshop 1 completed with standardized tools (@jonleung, ~~hackclub/hackclub#648~~ hackclub/hackclub#677)
- [ ] Workshop 2 completed with standardized tools (@jonleung, hackclub/hackclub#649)
- [ ] Holiday update (@zachlatta, hackclub/meta#368)
- [ ] Curriculum arc for semester (@jonleung, hackclub/hackclub#663)
- [x] 3rd meeting guide (@zachlatta (with help from @paked), hackclub/hackclub#666)

**Comment by zachlatta** [comment]
Replaced by #486.
