### ISSUE TITLE
Week of 02.01.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#486]
- [x] Workshop 2 completed with standardized tools (@jonleung, hackclub/hackclub#649)
- [ ] Holiday update (@zachlatta, hackclub/meta#368)
- [x] Curriculum arc for semester (@jonleung, hackclub/hackclub#663)
- [ ] Create 4th meeting template (@zachlatta, hackclub/hackclub#680)
- [ ] Begin work on new 3rd workshop (@jonleung, hackclub/hackclub#681) (this isn't due until the 15th)

**Comment by MaxWofford** [comment]
@zachlatta Want to close this?

/cc @prophetorpheus

**Comment by zachlatta** [comment]
Ah, thank you! Closing now.
