### ISSUE TITLE
Week of 04.04.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#525]
This issue is to track everything we want to do this week.

#### Content

- [x] Complete Dodge rewrite (hackclub/hackclub#522, @jkwok91)
- [ ] Create first "Coding is..." workshop (hackclub/hackclub#779, @jkwok91)

#### Website

- [x] Improve donation page (hackclub/website#217, @zachlatta)
- [x] Close applications for this school year (hackclub/website#216, @zachlatta)
- [x] Change year selector to be international friendly (hackclub/website#201,
  @zachlatta)

#### Organization Growth

- [x] Investigate getting our own 501(c)(3) status (hackclub/meta#521, @zachlatta)
- [ ] Get first date confirmed for Shasta club (hackclub/meta#522, @zachlatta)
- [x] De-onboard Jonathan (hackclub/meta#519, @zachlatta)
- [x] De-onboard Zach Bruggeman (hackclub/meta#520, @zachlatta)
- [x] Write full requirements for curriculum engineer position (hackclub/meta#523, @zachlatta)

#### Events

- [ ] Have dates and structure set for Hack Camp (hackclub/hack-camp#536, @zachlatta)
- [x] Organize Hack Night for next weekend (hackclub/meta#524, @zachlatta)

/cc @hackclub/staff

**Comment by zachlatta** [comment]
Closing because week is over. New weekly in #537.
