### ISSUE TITLE
Week of 04.11.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#529]
#### Curriculum

- [ ] Finish Soundboard workshop (hackclub/hackclub#784, @jkwok91)
- [x] Come up with idea for other "Coding Is..." workshop (comment in hackclub/hackclub#778, @jkwok91)
- [ ] Start brainstorming first deep dive (comment results in hackclub/hackclub#778, @jkwok91 (with help from @zachlatta))

#### Shasta Club

- [ ] Get first date confirmed (hackclub/meta#522, @jkwok91 (with help from @zachlatta))

#### Organization

- [ ] Reconcile our finances (hackclub/finances#12, @jkwok91)
- [ ] Get a lawyer to work with for our 501(c)(3) status (hackclub/meta#521, @zachlatta)

#### Website

- [x] Implement sweet new donation page (hackclub/website#217, @zachlatta)

**Comment by jkwok91** [comment]
The other "Coding is..." is geometric patterns in p5.js

**Comment by jkwok91** [comment]
Btw: https://gist.github.com/jkwok91/8824a5ecc915abc1675e286cf8e64029
Brainstorm

**Comment by zachlatta** [comment]
Can you make an issue to track creating that workshop?

On Fri, Apr 15, 2016 at 12:06 AM, JESSICA <notifications@github.com> wrote:

> Btw: https://gist.github.com/jkwok91/8824a5ecc915abc1675e286cf8e64029
> Brainstorm
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/529#issuecomment-210318899>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
Yea but what about all the stuff we did that's not on this list 🍭

**Comment by zachlatta** [comment]
Yeah, but we should strive to accomplish everything on the list in addition
to the other stuff. Let's do better this week.

On Mon, Apr 18, 2016 at 1:48 PM, JESSICA <notifications@github.com> wrote:

> Yea but what about all the stuff we did that's not on this list 🍭
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/529#issuecomment-211569346>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Closing because week is over. New weekly in #537.

**Comment by MaxWofford** [comment]
Closing because @zachlatta is [closing this](https://github.com/hackclub/meta/issues/529#issuecomment-212160380) because #537

**Comment by zachlatta** [comment]
:ok_hand:

Thanks Max, totally forgot to hit that close button.

On Tue, Apr 19, 2016 at 4:04 PM, Max Wofford <notifications@github.com>
wrote:

> Closing because @zachlatta <https://github.com/zachlatta> is closing this
> <https://github.com/hackclub/meta/issues/529#issuecomment-212160380>
> because #537 <https://github.com/hackclub/meta/issues/537>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/529#issuecomment-212161660>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
