### ISSUE TITLE
Organize Shasta Club's next meeting

### ISSUE THREAD

**Issue by jkwok91** [hackclub/meta#531]
Hack Club is helping to run the coding club at Summit High School: Shasta, and for their next meeting we've decided to have an event, in the hopes of attracting new members!

#### Event

We'll be running the Personal Website workshop for beginners who show up.

**Todo:**
- [x] Consider amending the workshop, or creating a branch of it to:
  - [ ] Introduce more HTML elements
  - [ ] Add more websites for inspiration
- [ ] For anyone more advanced, we should have something prepared to have them try. CSS animations?
- [x] Prepare a slideshow
- [x] Anticipate FAQs
- [ ] Make sure I know how to handle workflows that I don't use, like GitHub web interface.

#### Marketing

**Todo:**
- [x] Poster for this event to post at Shasta
- [ ] Informational flyer about Hack Club's online community? And recurring events?
- [ ] Email?
- [x] Bring stickers

#### Other

**Todo:**
- [x] Finish https://github.com/hackclub/meta/issues/522
- [ ] Make sure we get in touch with a teacher sponsor (do we need to do this?) and make sure that the event times are kosher
- [x] Pizza

**Comment by zachlatta** [comment]
It'd probably be worth mentioning https://github.com/hackclub/meta/issues/522 from this issue as well – still have to get those TB tests done.

**Comment by MatthewKwong** [comment]
[Personal Website lesson](https://github.com/hackclub/hackclub/blob/master/workshops/personal_website/README.md) seems good to teach for beginners.  I really like the idea for CSS animations for more advanced people. 

My mentor is down for helping out, I can ask her if she can stay later after than 5 if needed. I can send you her email if needed.

Everything else sounds good! Excited for this to come together.  May 13th would be the best time to do this because Juniors have AP exams happening the week before and a bunch of prep events prior to the test.

**Comment by zachlatta** [comment]
Hmm, is there any earlier we could do it? We'd love to be able to get in a
few meetings before the school year ends.

On Sun, Apr 17, 2016 at 4:40 PM, Matthew Kwong <notifications@github.com>
wrote:

> Personal Website lesson
> <https://github.com/hackclub/hackclub/blob/master/workshops/personal_website/README.md>
> seems good to teach for beginners. I really like the idea for CSS
> animations for more advanced people.
>
> My mentor is down for helping out, I can ask her if she can stay later
> after than 5 if needed. I can send you her email if needed.
>
> Everything else sounds good! Excited for this to come together. May 13th
> would be the best time to do this because Juniors have AP exams happening
> the week before and a bunch of prep events prior to the test.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/531#issuecomment-211129223>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
@MatthewKwong: I think @jkwok91 is currently in touch with you on Slack about coordinating for the date.

@jkwok91: can you post any updates from Slack here as soon as you have them?

**Comment by zachlatta** [comment]
Okay, so we're set to run it on this Thursday, the 28th.

Quick overview of where we're at:

- We're going to be running the Personal Website workshop, per @MatthewKwong's suggestion
- @jkwok91 made a bunch of dope posters that @MatthewKwong is going to put around the school
  - @MatthewKwong is also going to pass out Hack Club stickers to advertise

**Comment by zachlatta** [comment]
It's been done! Great work team.

:tada: :tada: :tada:
