### ISSUE TITLE
Week of 04.18.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#537]
#### What We Didn't Accomplish Last Week (or the Previous)

All the things we didn't accomplish in previous weekly issues. We're going to tackle these this week.

#### 04.11.16

- [ ] Finish Soundboard workshop (hackclub/hackclub#784, @jkwok91)
- [x] Start brainstorming first deep dive (comment results in hackclub/hackclub#778, @jkwok91 (with help from @zachlatta))
- [x] Get first date confirmed (hackclub/meta#522, @jkwok91 (with help from @zachlatta))
- [x] Reconcile our finances (hackclub/finances#12, @jkwok91)
- [ ] Get a lawyer to work with for our 501(c)(3) status (hackclub/meta#521, @zachlatta)
- [x] Have dates and structure set for Hack Camp (hackclub/hack-camp#536, @zachlatta)

#### 04.04.16

Nothing that wasn't completed or transferred to 04.11.16.

#### This Week

@jkwok91's goals:

- Organize upcoming Hack Night
- Prepare and setup for Shasta meeting happening next week (this includes getting TB test done)
- Conquer backlog from previous weeks

@zachlatta's goals:

- Make progress on organizing Hack Camp. "Get it together and figured out."
  - Same thing for Demo Night
- Get 501(c)(3) status in order

##### Shasta Club

- [x] Start marketing the upcoming meeting (@jkwok91, hackclub/meta#531)

##### Hack Night

- [x] Send out recap email for 04.16.16 Hack Night (@zachlatta, hackclub/meta#536)
- [x] Send out email about upcoming Hack Night (@jkwok91, hackclub/meta#530)
- [x] Create Hack Night stickers (@jkwok91, hackclub/meta#535)

##### Hack Camp

- [ ] Figure out staffing and financials (@zachlatta, hackclub/hack-camp#540)

##### Demo Night

- [x] Secure a food sponsor (@zachlatta, hackclub/meta#534)
- [x] Find speakers (@zachlatta, hackclub/meta#534)

##### Backlog

- [ ] Get a lawyer to work with on our 501(c)(3) status (@zachlatta, hackclub/meta#521)
- [ ] Finish Soundboard workshop (hackclub/hackclub#784, @jkwok91)
- [x] Start brainstorming first deep dive (comment results in hackclub/hackclub#778, @jkwok91 (with help from @zachlatta))
- [x] Get first date confirmed (hackclub/meta#522, @jkwok91 (with help from @zachlatta))
- [x] Reconcile our finances (hackclub/finances#12, @jkwok91)

**Comment by zachlatta** [comment]
Closing because week is over. New issue in #541.
