### ISSUE TITLE
Week of 04.25.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#541]
#### Workshops

- [ ] ~~Add GitHub's third signup step to Personal Website (@jkwok91, hackclub/hackclub#798)~~
- [x] Make a round of improvements to Soundboard (wasn't completed last week) (@jkwok91, hackclub/hackclub#805)
- [x] Create workshop on Bootstrap (@jkwok91, hackclub/hackclub#807)

#### Events

- [x] Run the Shasta club meeting (@jkwok91, hackclub/meta#531)
- [x] Market and run Hack Night (@jkwok91, hackclub/meta#530)
  - [x] Get at least ~~three~~ two in-person meetups happening (@zachlatta, tracked in hackclub/meta#530)

#### Hack Camp

- [ ] Reach out to 5 venues by end of Tuesday, April 26th (@zachlatta, tracked [here](https://github.com/hackclub/hackcamp/issues/544#issuecomment-214814375))
- [ ] Get to "in talks" with 5 venues (@zachlatta, tracked [here](https://github.com/hackclub/hackcamp/issues/544#issuecomment-214814375))
- [x] Figure out staffing and financials (wasn't completed last week) (@zachlatta, hackclub/hackcamp#540)
- [x] Set time for weekly staff meeting (@MaxWofford, hackclub/hackcamp#547)
- [x] Launch website with application by Thursday, April 28th (@MaxWofford, hackclub/hackcamp#541 and hackclub/hackcamp#543)
- [x] Launch Hack Camp by Thursday, April 28th (@MaxWofford, hackclub/hackcamp#546)
- [ ] ~~Drive 15 applications (@MaxWofford, hackclub/hackcamp#548)~~

#### Meta

- [x] Create clearer instructions for how to use GitHub web interface (@jkwok91, hackclub/hackclub#796)
- [x] Start transitioning senior club leadership (@zachlatta, hackclub/meta#540)
- [ ] Get a lawyer to work with for our 501(c)(3) status (wasn't completed last week) (@zachlatta, hackclub/meta#521)
- [x] Figure out and confirm housing situation for Max (@zachlatta, hackclub/meta#544)

**Comment by jkwok91** [comment]
This is over! We need a new weekly.

**Comment by zachlatta** [comment]
Closing because week is over. New weekly in #551.
