### ISSUE TITLE
Week of 05.02.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#551]
It's May! Apologies for the delay in creating this – will reach out to everyone about making issues for each task.

#### Curriculum

- Finish Soundboard workshop
  - [ ] get better sounds
  - [ ] remove refactoring section
  - [ ] add more buttons
  - [ ] add CSS because no one is using this thing like a soundboard cuz it doesn't look like one
- [x] Write first draft of Geometric Pattern workshop with p5.js https://github.com/hackclub/hackclub/pull/823
- Test with Julia on Sunday
- Test with rest of user-testing group
- Come up with idea for developing Dodge for Deep Dive 1.
- Come up with ideas for electives, possibly using an API

#### Hack Camp

- [ ] Facebook ads (@zachlatta)
- [ ] Make significant progress on venue (@zachlatta)
- [ ] 5 venues in talks (@zachlatta)
- [x] Send out community email (@zachlatta)
- [x] Concrete timeline for curriculum (@jkwok91)
- [ ] One more workshop done (@jkwok91)
- [ ] Logo finished (@jkwok91)
- [ ] Posters finished (@jkwok91)
- [x] SFUSD Bulletin board (@MaxWofford, hackclub/hackcamp#589)
- [ ] Acquire 15 viable signups(@MaxWofford, hackclub/hackcamp#575)
- [x] Blog post about Hack Camp (@MaxWofford, hackclub/blog#24)
- [ ] Get Sooz to post in parent mailing lists (@MaxWofford, hackclub/hackcamp#577)
- [x] Update financials in Google Drive (@MaxWofford, hackclub/hackcamp#540)
- [ ] Send info packet to volunteers (@MaxWofford, hackclub/hackcamp#585)
- [ ] Finalize plan for in-person ads at SFUSD (@ssun098)
- [ ] Reach out to assigned venues (@ssun098)

#### Meta

- [ ] 501(c)(3) status lawyer (@zachlatta, hackclub/meta#521)
- [ ] Create clearer instructions for how to use GitHub web interface (@jkwok91, hackclub/hackclub#796)

**Comment by zachlatta** [comment]
Going to go ahead and close this because the week's over.

**Comment by zachlatta** [comment]
Replaced by https://github.com/hackclub/meta/issues/554.
