### ISSUE TITLE
Week of 05.09.16

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#554]
This weekly's going to be much shorter than that of previous weeks.

Three categories of objectives: curriculum, Hack Camp, and meta.

### Curriculum

See the May 9 - 15 section of https://github.com/hackclub/hackclub/issues/778. @jkwok91 is responsible for making sure this gets done.

### Hack Camp

See the May 8 - 14 section of https://github.com/hackclub/hackcamp/issues/597. @MaxWofford is responsible for making sure these get done.

### Meta

- [x] Transition leadership in clubs led by seniors (https://github.com/hackclub/meta/issues/540, @zachlatta)
- [x] Run this weekend's Demo Night (https://github.com/hackclub/meta/issues/534, @zachlatta)
- [x] Secure lawyer for 501(c)(3) status (https://github.com/hackclub/meta/issues/521, @zachlatta)
- [ ] Update press logos on website (https://github.com/hackclub/website/issues/209, @zachlatta)

/cc @hackclub/staff

**Comment by jkwok91** [comment]
You still wanna do first hack day after deep dive?

**Comment by MaxWofford** [comment]
@zrl: is it cool if we close this?

**Comment by zachlatta** [comment]
Done!
