### ISSUE TITLE
Organize July Hack Series/Demo Night

### ISSUE THREAD

**Issue by ssun098** [hackclub/meta#561]
This issue is for tracking everything that needs to be done for Hack Series and Demo Night in July, and will be regularly updated!

Hack Series
- [x] Get venue (#567, @ssun098)
- [x] Find a few more people for team (#568, @ssun098)
- [x] Create Facebook/Eventbrite events (#569, @ssun098)
- [x] Mentors (#580, @MaxWofford)
- [x] Sign ups (#572, @ssun098)
- [x] Schedule (#581, @MaxWofford)
- [x] Update subdomain for Hack Series (#582, @zachlatta)
- [x] Send out text to all Hack Series attendees in the morning (#606, @MaxWofford)

Demo Night
- [x] Get venue (#567, @ssun098)
- [x] Create Facebook/Eventbrite events (#569, @ssun098)
- [x] Keynote (#583, @zachlatta)
- [x] Short-talk (#585, @zachlatta)
- [x] Schedule (#573, @ssun098)
- [ ] Sign ups (#575, @ssun098)
- [x] Sign ups from people who want to demo (#574, @ssun098)
- [x] Update subdomain for Demo Night (#586, @zachlatta)
- [x] Get bio for Oz (#595, @zachlatta)
- [ ] Get cups and label maker (#605, @ssun098)

**Comment by zachlatta** [comment]
:raised_hands:

**Comment by MaxWofford** [comment]
I've removed the local press task – I don't think it's worth our time right now.

**Comment by ssun098** [comment]
epic feelsbadman
