### ISSUE TITLE
Organize Hack Night

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#588]
Discussion about organizing Hack Night is happening in [#hack-night-organizers](https://starthackclub.slack.com/messages/hack-night-organizers/). This is our list of tasks.

- [x] Decide on a date (#589)
- [x] Choose a theme (#590)
- [x] Have a checklist/schedule of the event (#591)
- [x] Make an announcement about Hack Night in #hack-night and #announcements (#592)
- [x] Get list of Hack Night Summer meetups that have 5 or more participants (#607)
- [x] Send out an email after the event with links to all the projects (#609)
